"use client";
import { useState, type FormEvent } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api/client";
import { useCompany } from "@/lib/api/hooks";
import { PageHeading } from "@/components/shared-pages";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { Button, Field, Input, Switch } from "@/components/ui/controls";
import { valueOf } from "../common";
export function ConfiguracoesForm() { const company = useCompany(); const cache = useQueryClient(); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); if (company.isLoading) return <p>Carregando configurações…</p>; async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const form = new FormData(event.currentTarget); try { await api("/company", { method: "PATCH", body: JSON.stringify({ name: valueOf(form, "name"), document: valueOf(form, "document") || undefined, financialEmail: valueOf(form, "financialEmail") || undefined, logoUrl: valueOf(form, "logoUrl") || undefined, currency: "BRL", timezone: "America/Sao_Paulo", reminderEnabled: form.get("reminderEnabled") === "on", reminderDaysBefore: Number(valueOf(form, "reminderDaysBefore")) }) }); await cache.invalidateQueries({ queryKey: ["company"] }); setMessage("Configurações salvas."); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível salvar."); } finally { setPending(false); } } const current = company.data; return <div className="page-enter mx-auto max-w-5xl"><PageHeading eyebrow="Empresa" title="Configurações" description="Personalize os dados e lembretes da sua empresa." />{message && <p role="status" className="mb-4 rounded-xl bg-surface p-3 text-sm text-brand">{message}</p>}<Card><form onSubmit={submit}><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="Razão social ou nome" htmlFor="name"><Input id="name" name="name" required defaultValue={current?.name} /></Field><Field label="CPF ou CNPJ" htmlFor="document"><Input id="document" name="document" defaultValue={current?.document} /></Field><Field label="E-mail financeiro" htmlFor="financialEmail"><Input id="financialEmail" name="financialEmail" type="email" defaultValue={current?.financialEmail} /></Field><Field label="URL do logotipo" htmlFor="logoUrl"><Input id="logoUrl" name="logoUrl" type="url" defaultValue={current?.logoUrl} /></Field><Field label="Avisar com antecedência de quantos dias" htmlFor="reminderDaysBefore"><Input id="reminderDaysBefore" name="reminderDaysBefore" type="number" min="0" max="90" defaultValue={current?.reminderDaysBefore ?? 3} /></Field><div className="pt-6"><Switch name="reminderEnabled" label="Ativar lembretes" defaultChecked={current?.reminderEnabled} /></div></CardContent><CardFooter className="flex justify-end"><Button disabled={pending}>{pending ? "Salvando…" : "Salvar configurações"}</Button></CardFooter></form></Card></div>; }
