ALTER TYPE "AccountType" RENAME VALUE 'BANK' TO 'CONTA_CORRENTE';
ALTER TYPE "AccountType" RENAME VALUE 'CASH' TO 'CONTA_PAGAMENTO';
ALTER TYPE "AccountType" ADD VALUE 'CONTA_POUPANCA';
ALTER TYPE "AccountType" ADD VALUE 'CONTA_SALARIO';
ALTER TYPE "AccountType" ADD VALUE 'CONTA_PJ';
