'use client';
/* oxlint-disable typescript/unbound-method */

import Link from 'next/link';
import { ArrowRight, BellRing, CalendarClock, Check, Eye, EyeOff, History, Leaf } from 'lucide-react';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api/client';
import type { Page } from '@/lib/api/generated';
import { useAuth } from './app-providers';
import { PageHeading, StatusPill } from './shared-pages';

export function LoginPage(){const {login}=useAuth();const[show,setShow]=useState(false);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const submit=async(e:React.SyntheticEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const email=f.get('email');const password=f.get('password');setBusy(true);setError('');try{await login(typeof email==='string'?email:'',typeof password==='string'?password:'')}catch(err){setError(err instanceof Error?err.message:'Não foi possível entrar.')}finally{setBusy(false)}};return <main className="grid min-h-screen bg-[#F6FAF3] lg:grid-cols-[minmax(0,1.05fr)_minmax(440px,.95fr)]"><section className="relative hidden bg-[#1F2A1E] p-12 text-white lg:flex lg:flex-col"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-[#8AAE6D] text-[#1F2A1E]"><Leaf className="size-5"/></span><div><p className="font-semibold">Verde Caixa</p><p className="text-xs text-white/50">Finanças claras</p></div></div><div className="my-auto max-w-lg"><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#AFCB98]">Controle sem complicação</p><h1 className="mt-4 text-4xl font-semibold leading-tight">Clareza para cuidar do caixa e decidir com confiança.</h1><p className="mt-5 text-sm leading-7 text-white/60">Organize contas, vencimentos e resultados em um ambiente seguro.</p></div></section><section className="flex items-center justify-center p-6"><div className="w-full max-w-[410px]"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#8AAE6D]">Bem-vindo</p><h2 className="mt-2 text-3xl font-semibold">Acesse sua empresa</h2><p className="mt-2 text-sm text-[#60705E]">Informe as credenciais configuradas no ambiente.</p>{error&&<div className="mt-5 rounded-xl bg-[#F7EDEA] px-4 py-3 text-sm text-[#A14E42]">{error}</div>}<form className="mt-8 space-y-5" onSubmit={submit}><label className="block text-xs font-semibold">E-mail<input name="email" type="email" required className="mt-1.5 h-12 w-full rounded-xl border bg-white px-3 text-sm"/></label><label className="block text-xs font-semibold">Senha<span className="relative mt-1.5 block"><input name="password" type={show?'text':'password'} required className="h-12 w-full rounded-xl border bg-white px-3 pr-11 text-sm"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-1.5 top-1/2 grid size-9 -translate-y-1/2 place-items-center" aria-label={show?'Ocultar senha':'Mostrar senha'}>{show?<EyeOff className="size-4"/>:<Eye className="size-4"/>}</button></span></label><button disabled={busy} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#3E5A3C] text-sm font-semibold text-white disabled:opacity-60">{busy?'Entrando…':'Entrar'}<ArrowRight className="size-4"/></button></form></div></section></main>}

interface Notification {id:string;title:string;message:string;createdAt:string;readAt?:string;type:string}
export function NotificationsPage(){const qc=useQueryClient();const result=useQuery({queryKey:['notifications'],queryFn:()=>api<Page<Notification>>('/notifications?limit=100')});const readAll=useMutation({mutationFn:()=>api('/notifications/read-all',{method:'PATCH'}),onSuccess:()=>qc.invalidateQueries({queryKey:['notifications']})});return <div className="page-enter"><PageHeading eyebrow="Central" title="Notificações" description="Alertas sobre vencimentos, liquidações e acessos."/><section className="app-card overflow-hidden"><div className="flex justify-between border-b px-5 py-4"><p className="text-sm font-semibold">Mais recentes</p><button onClick={()=>readAll.mutate()} className="text-xs font-semibold text-[#3E5A3C]">Marcar todas como lidas</button></div>{result.isLoading?<Loading/>:result.isError?<ErrorState/>:<div className="divide-y">{result.data?.data.map(item=><article key={item.id} className={`flex gap-3 p-4 sm:px-5 ${!item.readAt?'bg-[#FBFDF9]':''}`}><span className="grid size-10 place-items-center rounded-xl bg-[#E8F1E1] text-[#3E5A3C]">{item.type==='SETTLEMENT'?<Check className="size-4"/>:<CalendarClock className="size-4"/>}</span><div className="flex-1"><div className="flex justify-between gap-3"><p className="text-sm font-semibold">{item.title}</p><span className="text-[11px] text-[#8A9688]">{new Date(item.createdAt).toLocaleString('pt-BR')}</span></div><p className="mt-1 text-xs text-[#60705E]">{item.message}</p></div>{!item.readAt&&<span className="mt-2 size-2 rounded-full bg-[#8AAE6D]"/>}</article>)}</div>}</section></div>}

interface Audit {id:string;summary:string;action:string;entityType:string;createdAt:string;actor?:{name:string;email:string}}
export function HistoryPage(){const[search,setSearch]=useState('');const result=useQuery({queryKey:['audit',search],queryFn:()=>api<Page<Audit>>(`/audit-logs?limit=100&search=${encodeURIComponent(search)}`)});return <div className="page-enter"><PageHeading eyebrow="Auditoria" title="Histórico de alterações" description="Registro das ações realizadas pela equipe."/><section className="app-card overflow-hidden"><div className="border-b p-4"><label className="relative block max-w-md"><History className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#849081]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar histórico..." className="h-10 w-full rounded-xl border bg-[#FBFDF9] pl-9 pr-3 text-sm"/></label></div>{result.isLoading?<Loading/>:result.isError?<ErrorState/>:<div className="divide-y">{result.data?.data.map(item=><article key={item.id} className="flex gap-4 p-4 sm:px-5"><span className="grid size-10 place-items-center rounded-full bg-[#E8F1E1] text-xs font-bold text-[#3E5A3C]">{item.actor?.name.split(' ').map(x=>x[0]).slice(0,2).join('')??'VC'}</span><div className="flex-1"><p className="text-sm"><strong>{item.actor?.name??'Sistema'}</strong> <span className="text-[#60705E]">{item.summary}</span></p><p className="mt-1 text-xs text-[#71806F]">{item.entityType}</p></div><div className="text-right"><StatusPill status={item.action}/><p className="mt-1 text-[11px] text-[#8A9688]">{new Date(item.createdAt).toLocaleString('pt-BR')}</p></div></article>)}</div>}</section></div>}

export function NotFoundPage(){return <div className="page-enter grid min-h-[65vh] place-items-center text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#E8F1E1] text-[#3E5A3C]"><BellRing className="size-6"/></span><h2 className="mt-4 text-xl font-semibold">Página não encontrada</h2><Link href="/dashboard" className="mt-5 inline-flex h-10 items-center rounded-xl bg-[#3E5A3C] px-4 text-sm font-semibold text-white">Voltar ao início</Link></div></div>}
function Loading(){return <div className="p-12 text-center text-sm text-[#60705E]">Carregando…</div>}function ErrorState(){return <div className="p-12 text-center text-sm text-[#A14E42]">Não foi possível carregar os dados.</div>}
