'use client';
/* oxlint-disable typescript/no-explicit-any */

import Link from 'next/link';
import { ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, Download, FileSpreadsheet, LineChart, TrendingUp, WalletCards } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api, download } from '@/lib/api/client';
import { PageHeading } from './shared-pages';
import { ClientOnly } from './client-only';

const currency = (value: string | number) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value));
const cards=[{slug:'dre',title:'DRE gerencial',description:'Receitas, despesas e resultado pelo regime de caixa.',icon:FileSpreadsheet},{slug:'dfc',title:'DFC — Fluxo de caixa',description:'Entradas e saídas efetivamente liquidadas.',icon:LineChart},{slug:'posicao-financeira',title:'Posição financeira',description:'Saldos, direitos e obrigações da empresa.',icon:WalletCards},{slug:'kpis',title:'Painel de indicadores',description:'Principais sinais financeiros do negócio.',icon:BarChart3}];

export function ReportsHub(){return <div className="page-enter"><PageHeading eyebrow="Análises" title="Relatórios" description="Leituras financeiras calculadas com os dados reais da empresa."/><section className="grid gap-4 sm:grid-cols-2">{cards.map(({slug,title,description,icon:Icon})=><Link key={slug} href={`/relatorios/${slug}`} className="app-card group p-5 sm:p-6"><div className="flex"><span className="grid size-12 place-items-center rounded-2xl bg-[#E8F1E1] text-[#3E5A3C]"><Icon className="size-5"/></span><ArrowRight className="ml-auto size-4 text-[#9AA49A]"/></div><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-1.5 text-sm text-[#60705E]">{description}</p></Link>)}</section></div>}

export function ReportPage({kind}:{kind:string}){
  const report=useQuery({queryKey:['report',kind],queryFn:()=>api<any>(`/reports/${kind}`)});
  if(report.isLoading)return <div className="p-12 text-center text-sm text-[#60705E]">Calculando relatório…</div>;
  if(report.isError||!report.data)return <div className="app-card p-8 text-center">Não foi possível calcular o relatório.</div>;
  const data=report.data; const title=cards.find(x=>x.slug===kind)?.title??'Relatório';
  return <div className="page-enter"><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/relatorios" className="text-xs font-semibold text-[#60705E]">← Todos os relatórios</Link><h2 className="mt-3 text-2xl font-semibold">{title}</h2><p className="mt-1 text-sm text-[#60705E]">Dados atualizados pelo regime de caixa.</p></div><div className="flex gap-2"><button onClick={()=>void download(`/reports/${kind}/export?format=csv`)} className="inline-flex h-10 items-center gap-2 rounded-xl border px-3 text-xs font-semibold"><Download className="size-4"/>CSV</button><button onClick={()=>void download(`/reports/${kind}/export?format=pdf`)} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#3E5A3C] px-3 text-xs font-semibold text-white"><Download className="size-4"/>PDF</button></div></header>{kind==='dre'?<Dre data={data}/>:kind==='dfc'?<Dfc data={data}/>:kind==='posicao-financeira'?<Position data={data}/>:<Kpis data={data}/>}</div>;
}

function Dre({data}:{data:any}){return <section className="app-card overflow-hidden"><Line label="Receitas totais" value={data.income}/><Line label="Despesas totais" value={data.expense} negative/><Line label="Resultado líquido" value={data.result} strong/>{data.lines?.map((x:any)=><Line key={x.label} label={x.label} value={x.value} negative={Number(x.value)<0}/>)}</section>}
function Dfc({data}:{data:any}){return <section className="app-card overflow-hidden"><Line label="Recebimentos" value={data.income}/><Line label="Pagamentos" value={data.expense} negative/><Line label="Variação líquida" value={data.netChange}/><Line label="Saldo final" value={data.finalBalance} strong/></section>}
function Position({data}:{data:any}){return <section className="grid gap-4 sm:grid-cols-2"><Metric title="Caixa e bancos" value={data.balance} icon={WalletCards}/><Metric title="A receber" value={data.receivable} icon={ArrowUpRight}/><Metric title="A pagar" value={data.payable} icon={ArrowDownRight}/><Metric title="Posição líquida" value={data.netPosition} icon={TrendingUp}/></section>}
function Kpis({data}:{data:any}){const flow=(data.cashFlow??[]).map((x:any)=>({...x,income:Number(x.income),expense:Number(x.expense)}));return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Saldo disponível" value={data.balance} icon={WalletCards}/><Metric title="A receber" value={data.receivable} icon={ArrowUpRight}/><Metric title="A pagar" value={data.payable} icon={ArrowDownRight}/><Metric title="Resultado mensal" value={data.monthlyResult} icon={TrendingUp}/></section><section className="app-card mt-5 p-5"><h3 className="text-sm font-semibold">Receitas e despesas</h3><div className="mt-5 h-[300px]"><ClientOnly><ResponsiveContainer width="100%" height="100%"><BarChart data={flow}><CartesianGrid stroke="#E5EDE0" vertical={false}/><XAxis dataKey="month"/><YAxis tickFormatter={v=>`${v/1000}k`}/><Tooltip formatter={v=>currency(Number(v))}/><Bar dataKey="income" name="Receitas" fill="#3E5A3C"/><Bar dataKey="expense" name="Despesas" fill="#8AAE6D"/></BarChart></ResponsiveContainer></ClientOnly></div></section></>}
function Line({label,value,strong,negative}:{label:string;value:string;strong?:boolean;negative?:boolean}){return <div className={`flex justify-between px-5 py-4 ${strong?'bg-[#1F2A1E] text-white':''}`}><span className={strong?'font-semibold':'text-sm'}>{label}</span><span className={`font-semibold ${negative&&!strong?'text-[#A14E42]':''}`}>{negative?'- ':''}{currency(Math.abs(Number(value)))}</span></div>}
function Metric({title,value,icon:Icon}:{title:string;value:string;icon:any}){return <article className="app-card p-5"><span className="grid size-10 place-items-center rounded-xl bg-[#E8F1E1] text-[#3E5A3C]"><Icon className="size-4"/></span><p className="mt-4 text-xs text-[#60705E]">{title}</p><p className="mt-1 text-xl font-semibold">{currency(value)}</p></article>}
