'use client';
/* oxlint-disable typescript/no-explicit-any, typescript/unbound-method */

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, Pencil, Plus, Search, SlidersHorizontal, Trash2 } from 'lucide-react';
import { api } from '@/lib/api/client';
import { useAccounts, useDirectory, useEntries, useSettleEntry } from '@/lib/api/hooks';
import type { ApiEntry } from '@/lib/api/generated';
import { ConfirmDialog } from './confirm-dialog';

const currency = (value: string | number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value));
const statusLabel: Record<string, string> = { PENDING: 'Pendente', OVERDUE: 'Vencido', SETTLED: 'Liquidado', CANCELED: 'Cancelado', ACTIVE: 'Ativo', INACTIVE: 'Inativo', IN_PROGRESS: 'Em andamento', COMPLETED: 'Concluído', PAUSED: 'Pausado' };

export function PageHeading({ eyebrow, title, description, actionHref, actionLabel }: { eyebrow?: string; title: string; description: string; actionHref?: string; actionLabel?: string }) {
  return <header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow && <p className="text-xs font-semibold uppercase tracking-[.12em] text-[#8AAE6D]">{eyebrow}</p>}<h2 className="mt-1 text-2xl font-semibold tracking-[-0.035em]">{title}</h2><p className="mt-1.5 max-w-2xl text-sm text-[#60705E]">{description}</p></div>{actionHref && actionLabel && <Link href={actionHref} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#3E5A3C] px-4 text-sm font-semibold text-white"><Plus className="size-4" />{actionLabel}</Link>}</header>;
}

export function StatusPill({ status }: { status: string }) {
  const label = statusLabel[status] ?? status;
  const tone = ['Liquidado', 'Ativo', 'Concluído'].includes(label) ? 'bg-[#E7F1DF] text-[#356333]' : ['Vencido', 'Inativo', 'Cancelado'].includes(label) ? 'bg-[#F7EDEA] text-[#A14E42]' : label === 'Em andamento' ? 'bg-[#E8F0F4] text-[#356278]' : 'bg-[#F4F0DF] text-[#806B25]';
  return <span className={`inline-flex h-6 items-center rounded-full px-2.5 text-[11px] font-semibold ${tone}`}>{label}</span>;
}

function Toolbar({ query, setQuery, status, setStatus }: { query: string; setQuery(v: string): void; status?: string; setStatus?(v: string): void }) {
  return <div className="flex flex-col gap-3 border-b border-[#E6EDE2] p-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#849081]"/><span className="sr-only">Pesquisar</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Pesquisar..." className="h-10 w-full rounded-xl border border-[#DCE6D6] bg-[#FBFDF9] pl-9 pr-3 text-sm outline-none"/></label>{status !== undefined && setStatus && <label className="relative"><span className="sr-only">Filtrar por situação</span><SlidersHorizontal className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#849081]"/><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-10 min-w-44 rounded-xl border border-[#DCE6D6] bg-white pl-9 pr-3 text-sm"><option>Todos</option><option value="PENDING">Pendente</option><option value="OVERDUE">Vencido</option><option value="SETTLED">Liquidado</option></select></label>}</div>;
}

export function FinancialList({ kind }: { kind: 'receber' | 'pagar' }) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('Todos');
  const result = useEntries(kind === 'receber' ? 'INCOME' : 'EXPENSE', query, status);
  const accounts = useAccounts(); const settle = useSettleEntry();
  const entries = result.data?.data ?? [];
  const total = entries.reduce((sum, item) => sum + Number(item.totalAmount), 0);
  const settleEntry = (entry: ApiEntry) => { const accountId = accounts.data?.data[0]?.id; const installmentId = entry.installments.find((item) => item.status === 'PENDING')?.id; if (accountId && installmentId) settle.mutate({ accountId, installmentId }); };
  return <div className="page-enter"><PageHeading eyebrow="Financeiro" title={`Contas a ${kind === 'receber' ? 'receber' : 'pagar'}`} description={kind === 'receber' ? 'Controle os valores que sua empresa tem a receber.' : 'Acompanhe compromissos e despesas liquidadas.'} actionHref={`/${kind}/novo`} actionLabel={kind === 'receber' ? 'Nova receita' : 'Nova despesa'}/>
    {settle.isError && <Notice error text={settle.error.message}/>}<section className="app-card overflow-hidden"><Toolbar query={query} setQuery={setQuery} status={status} setStatus={setStatus}/>{result.isLoading ? <Loading/> : result.isError ? <ErrorState/> : <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-[#F8FBF6] text-xs text-[#71806F]"><tr><th className="px-5 py-3">Lançamento</th><th className="px-4 py-3">Vencimento</th><th className="px-4 py-3">Categoria</th><th className="px-4 py-3">Situação</th><th className="px-4 py-3 text-right">Valor</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody className="divide-y divide-[#EAF0E6]">{entries.map((item) => <tr key={item.id}><td className="px-5 py-4"><p className="font-medium">{item.description}</p><p className="text-xs text-[#71806F]">{item.publicCode} · {item.counterparty.name}</p></td><td className="px-4 py-4">{new Date(item.dueDate).toLocaleDateString('pt-BR')}</td><td className="px-4 py-4">{item.category.name}</td><td className="px-4 py-4"><StatusPill status={item.status}/></td><td className="px-4 py-4 text-right font-semibold">{currency(item.totalAmount)}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Link href={`/${kind}/editar?id=${item.id}`} className="grid size-8 place-items-center rounded-lg hover:bg-[#EEF4EA]" aria-label="Editar"><Pencil className="size-3.5"/></Link>{['PENDING','OVERDUE'].includes(item.status) && <ConfirmDialog title="Confirmar liquidação?" description={`O valor será liquidado na conta ${accounts.data?.data[0]?.name ?? 'financeira selecionada'}.`} onConfirm={() => settleEntry(item)} trigger={<button className="grid size-8 place-items-center rounded-lg text-[#3E5A3C] hover:bg-[#E8F1E1]" aria-label="Liquidar"><Check className="size-4"/></button>}/>}</div></td></tr>)}</tbody><tfoot><tr className="border-t bg-[#FBFDF9]"><td colSpan={4} className="px-5 py-4 text-xs font-semibold">{entries.length} lançamentos</td><td className="px-4 py-4 text-right font-semibold">{currency(total)}</td><td><span className="sr-only">Ações</span></td></tr></tfoot></table></div><div className="divide-y md:hidden">{entries.map((item) => <article key={item.id} className="p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{item.description}</p><p className="mt-1 text-xs text-[#71806F]">{item.counterparty.name}</p></div><StatusPill status={item.status}/></div><div className="mt-4 flex justify-between"><span className="text-xs">{new Date(item.dueDate).toLocaleDateString('pt-BR')}</span><strong>{currency(item.totalAmount)}</strong></div><Link href={`/${kind}/editar?id=${item.id}`} className="mt-4 flex h-9 items-center justify-center rounded-lg border text-xs font-semibold">Editar</Link></article>)}</div>{!entries.length && <Empty/>}</>}</section></div>;
}

type DirectoryKind = 'clientes' | 'fornecedores' | 'categorias' | 'contas-financeiras' | 'projetos' | 'equipe' | 'perfis';
const meta: Record<DirectoryKind, [string,string,string,string]> = {
  clientes: ['Clientes','Empresas e pessoas que geram receitas.','/clientes/novo','Novo cliente'], fornecedores: ['Fornecedores','Fornecedores e prestadores ligados às despesas.','/fornecedores/novo','Novo fornecedor'], categorias: ['Categorias','Classificação dos lançamentos financeiros.','/categorias/nova','Nova categoria'], 'contas-financeiras': ['Contas financeiras','Saldos disponíveis em bancos e caixas.','/contas-financeiras/nova','Nova conta'], projetos: ['Projetos','Resultados por iniciativa.','/projetos/novo','Novo projeto'], equipe: ['Equipe','Pessoas com acesso ao financeiro.','/equipe/novo','Convidar pessoa'], perfis: ['Papéis e permissões','Conjuntos de acesso da equipe.','/perfis/novo','Novo papel'],
};

export function DirectoryList({ kind }: { kind: DirectoryKind }) {
  const [query, setQuery] = useState(''); const result = useDirectory(kind); const qc = useQueryClient();
  const paths: Record<string,string> = { clientes:'/clients', fornecedores:'/suppliers', categorias:'/categories', 'contas-financeiras':'/financial-accounts', projetos:'/projects', equipe:'/users', perfis:'/roles' };
  const remove = useMutation({ mutationFn: (id: string) => api(`${paths[kind]}/${id}`, { method: kind === 'equipe' ? 'PATCH' : 'DELETE', body: kind === 'equipe' ? JSON.stringify({ status: 'INACTIVE' }) : undefined }), onSuccess: () => qc.invalidateQueries({ queryKey: ['directory', kind] }) });
  const rows = useMemo(() => (result.data?.data ?? []).filter((row) => JSON.stringify(row).toLowerCase().includes(query.toLowerCase())), [query, result.data]);
  const [title, description, href, action] = meta[kind];
  const shape = (row: any) => kind === 'categorias' ? [row.name, row.kind === 'INCOME' ? 'Receita' : 'Despesa', `${row.children?.length ?? 0} subcategorias`, 'Ativo', ''] : kind === 'contas-financeiras' ? [row.name, `${row.institution} · ${row.type === 'BANK' ? 'Banco' : 'Caixa'}`, 'Saldo atual', 'Ativa', currency(row.balance)] : kind === 'projetos' ? [row.name, row.client?.name ?? 'Sem cliente', `${new Date(row.startsOn).toLocaleDateString('pt-BR')}`, row.status, currency(row.result)] : kind === 'perfis' ? [row.name, row.permissions?.join(', '), `${row.users} usuário(s)`, 'Ativo', ''] : kind === 'equipe' ? [row.name, row.email, row.role?.name ?? row.role, row.status, ''] : [row.name, row.document ?? '', row.email ?? '', row.deactivatedAt ? 'Inativo' : 'Ativo', ''];
  return <div className="page-enter"><PageHeading eyebrow="Cadastros" title={title} description={description} actionHref={href} actionLabel={action}/><section className="app-card overflow-hidden"><Toolbar query={query} setQuery={setQuery}/>{result.isLoading ? <Loading/> : result.isError ? <ErrorState/> : <div className="divide-y divide-[#EAF0E6]">{rows.map((row) => { const [a,b,c,d,e] = shape(row); return <article key={row.id} className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:px-5"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#EEF4EA] text-sm font-bold text-[#3E5A3C]">{String(a).slice(0,2).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{a}</p><p className="truncate text-xs text-[#71806F]">{b}</p></div><div className="sm:w-56"><p className="truncate text-xs text-[#71806F]">{c}</p>{e && <p className="font-semibold">{e}</p>}</div><StatusPill status={String(d)}/><div className="flex gap-1"><Link href={`/${kind}/editar?id=${row.id}`} className="grid size-9 place-items-center rounded-lg border" aria-label="Editar"><Pencil className="size-3.5"/></Link><ConfirmDialog destructive title={`Desativar ${a}?`} description="O registro deixará de aparecer em novas seleções." confirmLabel="Desativar" onConfirm={() => remove.mutate(row.id)} trigger={<button className="grid size-9 place-items-center rounded-lg border text-[#A14E42]" aria-label="Desativar"><Trash2 className="size-3.5"/></button>}/></div></article>; })}{!rows.length && <Empty/>}</div>}</section></div>;
}

export function AgendaPage() {
  const result = useQuery({ queryKey: ['agenda'], queryFn: () => api<any>('/agenda') });
  const groups = result.data ? [['Vencidos', result.data.overdue], ['Hoje', result.data.today], ['Próximos 7 dias', result.data.upcoming]] as const : [];
  return <div className="page-enter"><PageHeading eyebrow="Planejamento" title="Agenda financeira" description="Veja o que precisa da sua atenção e planeje os próximos dias."/>{result.isLoading ? <Loading/> : result.isError ? <ErrorState/> : <div className="space-y-5">{groups.map(([title, items]) => <section key={title}><div className="mb-2.5 flex items-center gap-2"><h3 className="text-sm font-semibold">{title}</h3><span className="text-xs text-[#8A9688]">{items.length}</span></div><div className="app-card divide-y">{items.map((item: any) => <div key={item.id} className="flex items-center gap-3 p-4"><span className={`grid size-10 place-items-center rounded-xl ${item.kind === 'INCOME' ? 'bg-[#E8F1E1] text-[#3E5A3C]' : 'bg-[#F4ECE8] text-[#9B5645]'}`}>{item.kind === 'INCOME' ? <ArrowUpRight className="size-4"/> : <ArrowDownRight className="size-4"/>}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.description}</p><p className="text-xs text-[#71806F]">{item.counterparty} · {item.category}</p></div><span className="hidden text-xs sm:block">{new Date(item.dueDate).toLocaleDateString('pt-BR')}</span><strong className="text-sm">{currency(item.amount)}</strong><ChevronRight className="size-4"/></div>)}</div></section>)}</div>}</div>;
}

function Loading() { return <div className="p-12 text-center text-sm text-[#60705E]">Carregando dados…</div>; }
function ErrorState() { return <div className="p-12 text-center"><p className="font-semibold">Não foi possível carregar os dados.</p><p className="mt-1 text-sm text-[#60705E]">Tente novamente em instantes.</p></div>; }
function Empty() { return <div className="p-12 text-center"><Search className="mx-auto size-5 text-[#8AAE6D]"/><p className="mt-3 text-sm font-semibold">Nenhum resultado encontrado</p></div>; }
function Notice({ error, text }: { error?: boolean; text: string }) { return <div className={`mb-4 rounded-xl px-4 py-3 text-sm ${error ? 'bg-[#F7EDEA] text-[#A14E42]' : 'bg-[#E8F1E1] text-[#356333]'}`}>{text}</div>; }
